export interface Subject {
    code: string;
    name: string;
    credits: number;
    type: "C" | "O" | "Non GPA";
}

export interface Program {
    name: string;
    semesters: {
        [key: string]: Subject[];
    };
}

export interface Programs {
    [key: string]: Program;
}

const programs: Programs = {
    ITT: {
        name: "Information Technology",
        semesters: {
            Y1S1: [
                {
                    code: "ICT 1111",
                    name: "Productivity Tools",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "ICT 1202",
                    name: "Electronic Circuits",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 1305",
                    name: "Program Designing and Programming",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1301",
                    name: "Fundamentals of Physics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1303",
                    name: "Fundamentals of Mathematics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CML 1201",
                    name: "Personality Development (Soft Skills)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1205",
                    name: "Communication Skills I (English)",
                    credits: 2,
                    type: "Non GPA",
                },
            ],
            Y1S2: [
                {
                    code: "ICT 1210",
                    name: "Introduction to Multimedia",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 1108",
                    name: "Skill Development Project I",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "ICT 1209",
                    name: "Web Technologies",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 1207",
                    name: "Human Computer Interaction",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ENT 1302",
                    name: "Fundamentals of Electricity and Magnetism",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "CMT 1209",
                    name: "Communication Skills II",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1203",
                    name: "Principles of Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1204",
                    name: "Health and Wellbeing",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1307",
                    name: "Mathematics for Technology I",
                    credits: 3,
                    type: "C",
                },
            ],
            Y2S1: [
                {
                    code: "ICT 2202",
                    name: "Operating Systems",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2303",
                    name: "Data Structures and Algorithm",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 2304",
                    name: "Object Oriented Programming",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 2207",
                    name: "Software System Design",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2202",
                    name: "Engineering Economics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 2202",
                    name: "Communication Skills III",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CMT 2306",
                    name: "Mathematics for Technology II",
                    credits: 3,
                    type: "O",
                },
            ],
            Y2S2: [
                {
                    code: "ICT 2305",
                    name: "Computational Mathematics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 2214",
                    name: "Introduction to the Information Systems",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2211",
                    name: "Fundamentals of Statistics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2213",
                    name: "Data Communication and Networking",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2308",
                    name: "Database Systems",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 2109",
                    name: "Communication and Learning Skills",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "CML 2204",
                    name: "Foreign Language",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2205",
                    name: "Ethics for Science and Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2212",
                    name: "Skills Development Project II",
                    credits: 2,
                    type: "C",
                },
            ],
            Y3S1: [
                {
                    code: "ICT 3201",
                    name: "Software Project Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3203",
                    name: "Scientific Computer Applications",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3206",
                    name: "Skills Development Project III",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3307",
                    name: "Computational Statistics",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 3208",
                    name: "Design and Analysis of Algorithms",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3312",
                    name: "Software Verification and Validation",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 3315",
                    name: "Internet of Things",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 3217",
                    name: "Advance Computer Networks",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 3218",
                    name: "Basics of Virtual Reality",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 3101",
                    name: "Legal and Patent Aspects",
                    credits: 1,
                    type: "C",
                },
            ],
            Y3S2: [
                {
                    code: "ICT 3209",
                    name: "Computer Organization and Architecture",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3310",
                    name: "Information Security",
                    credits: 3,
                    type: "C",
                },
                { code: "ICT 3311", name: "Robotics", credits: 3, type: "O" },
                {
                    code: "ICT 3315",
                    name: "Internet of Things",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 3213",
                    name: "Advanced SW System Design",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 3216",
                    name: "Research Methodology",
                    credits: 2,
                    type: "C",
                },
                { code: "ICT 3204", name: "E-Commerce", credits: 2, type: "C" },
                {
                    code: "CML 3203",
                    name: "Basics of Accountancy",
                    credits: 2,
                    type: "C",
                },
            ],
            Y4S1: [
                {
                    code: "ICT 4301",
                    name: "Mobile Computing",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 4302",
                    name: "Internet Applications",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ICT 4103",
                    name: "Software Engineering",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "ICT 4204",
                    name: "Graphics and Image Processing",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 4205",
                    name: "Current Topics in Information Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 4306",
                    name: "Data Science",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 4207",
                    name: "Artificial Intelligence",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 4201",
                    name: "Entrepreneurship",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 4202",
                    name: "Human Resource Management",
                    credits: 2,
                    type: "O",
                },
            ],
            Y4S2: [
                { code: "ICT 4808", name: "Project", credits: 8, type: "C" },
                {
                    code: "ICT 4609",
                    name: "Industrial Training",
                    credits: 6,
                    type: "C",
                },
            ],
        },
    },
    BPT: {
        name: "Bioprocess Technology",
        semesters: {
            Y1S1: [
                {
                    code: "CMT 1301",
                    name: "Fundamentals of Physics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1302",
                    name: "Fundamentals of Chemistry for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1303",
                    name: "Fundamentals of Mathematics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1304",
                    name: "Fundamentals of Computer for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1306",
                    name: "Fundamentals of Biology for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1205",
                    name: "Communication Skills I (English)",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1201",
                    name: "Personality Development (Soft Skills)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1202",
                    name: "Presentation Skills",
                    credits: 2,
                    type: "C",
                },
            ],
            Y1S2: [
                {
                    code: "BPT 1201",
                    name: "General Microbiology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 1202",
                    name: "Cell Biology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 1201",
                    name: "Organic Chemistry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1307",
                    name: "Mathematics for Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1208",
                    name: "Computer Programming for Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1209",
                    name: "Communication Skills II",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1203",
                    name: "Principles of Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1204",
                    name: "Health and Wellbeing",
                    credits: 2,
                    type: "C",
                },
            ],
            Y2S1: [
                {
                    code: "BPT 2201",
                    name: "Quality Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2202",
                    name: "Introduction to Bioprocess Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2203",
                    name: "Genetics and Evolution",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "BPT 2204",
                    name: "Plant Tissue Culture",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2205",
                    name: "Molecular Biology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2202",
                    name: "Basic Biochemistry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 2301",
                    name: "Fundamentals of Statistics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2306",
                    name: "Mathematics for Technology II",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "CMT 2202",
                    name: "Communication Skills III",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 2202",
                    name: "Engineering Economics",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2206",
                    name: "Indigenous Technology",
                    credits: 2,
                    type: "O",
                },
            ],
            Y2S2: [
                {
                    code: "BPT 2206",
                    name: "Bioreactor Operation and Design",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2207",
                    name: "Basic Immunology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2108",
                    name: "Quality Assurance and Safety of Bioprocessed Products",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "BPT 2209",
                    name: "Molecular Biotechnology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2305",
                    name: "Analytical Chemistry",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2203",
                    name: "Computational Mathematics",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2204",
                    name: "Foreign Language",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2205",
                    name: "Ethics in Science and Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2208",
                    name: "Introduction to Marketing",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S1: [
                {
                    code: "BPT 3201",
                    name: "Molecular Microbiology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 3302",
                    name: "Bioinformatics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 3203",
                    name: "Bioprocess Instrumentation and Control",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 3304",
                    name: "Molecular Modeling",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 3205",
                    name: "Bioprocess Optimization and Simulation",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 3206",
                    name: "Molecular Immunology and Current Applications",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 3207",
                    name: "Enzyme Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 3208",
                    name: "Industrial Microbiology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 3101",
                    name: "Legal and Patent Aspects",
                    credits: 1,
                    type: "C",
                },
            ],
            Y3S2: [
                { code: "BPT 3108", name: "Seminar", credits: 1, type: "C" },
                {
                    code: "BPT 3209",
                    name: "Scientific Writing",
                    credits: 2,
                    type: "C",
                },
                { code: "BPT 3610", name: "Internship", credits: 6, type: "C" },
                {
                    code: "CML 3102",
                    name: "Industrial Safety",
                    credits: 1,
                    type: "C",
                },
            ],
            Y4S1: [
                {
                    code: "BPT 4301",
                    name: "Drug Designing",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4302",
                    name: "Downstream Process Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4303",
                    name: "Bioremediation and Waste Management",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4204",
                    name: "Molecular Virology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4205",
                    name: "Plant Cell Culture",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4206",
                    name: "Pharmaceutical Biotechnology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4207",
                    name: "Bioproduct Development",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 4201",
                    name: "Entrepreneurship",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 4202",
                    name: "Human Resource Management",
                    credits: 2,
                    type: "O",
                },
            ],
            Y4S2: [
                {
                    code: "BPT 4808",
                    name: "Bioprocess Technology Project",
                    credits: 8,
                    type: "C",
                },
            ],
        },
    },
    FDT: {
        name: "Food Technology",
        semesters: {
            Y1S1: [
                {
                    code: "CMT 1301",
                    name: "Fundamentals of Physics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1302",
                    name: "Fundamentals of Chemistry for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1303",
                    name: "Fundamentals of Mathematics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1304",
                    name: "Fundamentals of Computer for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1306",
                    name: "Fundamentals of Biology for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1205",
                    name: "Communication Skills I (English)",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1201",
                    name: "Personality Development (Soft Skills)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1202",
                    name: "Presentation Skills",
                    credits: 2,
                    type: "C",
                },
            ],
            Y1S2: [
                {
                    code: "BPT 1201",
                    name: "General Microbiology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 1202",
                    name: "Cell Biology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 1201",
                    name: "Organic Chemistry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1307",
                    name: "Mathematics for Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1208",
                    name: "Computer Programming for Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1209",
                    name: "Communication Skills II",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1203",
                    name: "Principles of Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1204",
                    name: "Health and Wellbeing",
                    credits: 2,
                    type: "C",
                },
            ],
            Y2S1: [
                {
                    code: "FDT 2201",
                    name: "Physical Chemistry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2202",
                    name: "Basic Biochemistry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2203",
                    name: "Introduction to Food Industry",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2204",
                    name: "Food Preservation",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 2301",
                    name: "Fundamentals of Statistics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2306",
                    name: "Mathematics for Technology II",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "CMT 2202",
                    name: "Communication Skills III",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2206",
                    name: "Indigenous Technology",
                    credits: 2,
                    type: "O",
                },
            ],
            Y2S2: [
                {
                    code: "BPT 2206",
                    name: "Bioreactor Operation and Design",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2207",
                    name: "Basic Immunology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 2108",
                    name: "Quality Assurance and Safety of Bioprocessed Products",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "BPT 2209",
                    name: "Molecular Biotechnology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 2305",
                    name: "Analytical Chemistry",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2203",
                    name: "Computational Mathematics",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2204",
                    name: "Foreign Language",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2205",
                    name: "Ethics in Science and Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2208",
                    name: "Introduction to Marketing",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S1: [
                {
                    code: "FDT 3201",
                    name: "Fruits & Vegetables Processing Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3202",
                    name: "Food Engineering",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3203",
                    name: "Food Analysis",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3204",
                    name: "Meat and Fish Processing Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3205",
                    name: "Functional Food and Food Toxicology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3206",
                    name: "Dairy Product Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "FDT 3207",
                    name: "Confectionary and Beverage Technology",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "FDT 3108",
                    name: "Current Topics in Food Industry",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "FDT 3209",
                    name: "Cereals and Pulses Processing Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 3101",
                    name: "Legal and Patent Aspects",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "BPT 3207",
                    name: "Enzyme Technology",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S2: [
                { code: "BPT 3108", name: "Seminar", credits: 1, type: "C" },
                {
                    code: "BPT 3209",
                    name: "Scientific Writing",
                    credits: 2,
                    type: "C",
                },
                { code: "BPT 3610", name: "Internship", credits: 6, type: "C" },
                {
                    code: "CML 3102",
                    name: "Industrial Safety",
                    credits: 1,
                    type: "C",
                },
            ],
            Y4S1: [
                {
                    code: "BPT 4301",
                    name: "Drug Designing",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4302",
                    name: "Downstream Process Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4303",
                    name: "Bioremediation and Waste Management",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "BPT 4204",
                    name: "Molecular Virology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4205",
                    name: "Plant Cell Culture",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4206",
                    name: "Pharmaceutical Biotechnology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "BPT 4207",
                    name: "Bioproduct Development",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 4201",
                    name: "Entrepreneurship",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 4202",
                    name: "Human Resource Management",
                    credits: 2,
                    type: "O",
                },
            ],
            Y4S2: [
                {
                    code: "BPT 4808",
                    name: "Bioprocess Technology Project",
                    credits: 8,
                    type: "C",
                },
            ],
        },
    },
    EET: {
        name: "Electrical & Electronic Technology",
        semesters: {
            Y1S1: [
                {
                    code: "CMT 1301",
                    name: "Fundamentals of Physics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1302",
                    name: "Fundamentals of Chemistry for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1303",
                    name: "Fundamentals of Mathematics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1304",
                    name: "Fundamentals of Computer for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1205",
                    name: "Communication Skills I (English)",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1201",
                    name: "Personality Development (Soft Skills)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1202",
                    name: "Presentation Skills",
                    credits: 2,
                    type: "C",
                },
            ],
            Y1S2: [
                {
                    code: "ENT 1301",
                    name: "Introduction to Basic Electronics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ENT 1302",
                    name: "Fundamentals of Electricity and Magnetism",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1307",
                    name: "Mathematics for Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1208",
                    name: "Computer Programming for Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ENT 1204",
                    name: "Workshop Technology I",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1209",
                    name: "Communication Skills II",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1203",
                    name: "Principles of Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1204",
                    name: "Health and Wellbeing",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ENT 1203",
                    name: "Engineering Drawing",
                    credits: 2,
                    type: "C",
                },
            ],
            Y2S1: [
                {
                    code: "EET 2301",
                    name: "Digital & Analog Electronics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 2202",
                    name: "Electricity Network",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 2208",
                    name: "Introduction to Electrical Power",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 2204",
                    name: "Computer Aided Design (CAD)",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CMT 2306",
                    name: "Mathematics for Technology II",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2301",
                    name: "Fundamentals of Statistics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2202",
                    name: "Communication Skills III",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 2202",
                    name: "Engineering Economics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2206",
                    name: "Indigenous Technology",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "MTT 2204",
                    name: "Computer Aided Design (CAD)",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 2304",
                    name: "Object Oriented Programming",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 2202",
                    name: "Operating Systems",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 2303",
                    name: "Data Structures and Algorithm",
                    credits: 3,
                    type: "O",
                },
            ],
            Y2S2: [
                {
                    code: "EET 2203",
                    name: "Electronic Devices and Circuits",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 2204",
                    name: "Electrical Measurements and Instrumentation",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 2305",
                    name: "Electrical Machines",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 2206",
                    name: "Signals and Systems",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 2203",
                    name: "Computational Mathematics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2204",
                    name: "Foreign Language",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2205",
                    name: "Ethics in Science and Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2208",
                    name: "Introduction to Marketing",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 2207",
                    name: "Computer Aided Machine Design",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 2213",
                    name: "Data Communication and Networking",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S1: [
                {
                    code: "EET 3202",
                    name: "Communication Systems",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 3203",
                    name: "Computer Systems",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 3206",
                    name: "Automation Technology I",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 3210",
                    name: "Electrical Installations",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 3301",
                    name: "Electrical Power Systems",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 3304",
                    name: "Digital Signal Processing",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 3305",
                    name: "Control Systems",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CML 3101",
                    name: "Legal and Patent Aspects",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "ICT 3315",
                    name: "Internet of Things",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "ICT 3217",
                    name: "Advance Computer Networks",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S2: [
                {
                    code: "EET 3607",
                    name: "Industrial Training",
                    credits: 6,
                    type: "C",
                },
                {
                    code: "CML 3102",
                    name: "Industrial Safety",
                    credits: 1,
                    type: "C",
                },
            ],
            Y4S1: [
                {
                    code: "EET 4301",
                    name: "Electronic Circuit Design and Simulations",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 4303",
                    name: "Electrical Energy Utilization",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "EET 4304",
                    name: "Power Electronics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "EET 4818",
                    name: "Undergraduate Project",
                    credits: 4,
                    type: "C",
                },
                {
                    code: "EET 4202",
                    name: "Embedded System Design",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4305",
                    name: "Digital Communication",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "EET 4206",
                    name: "Automation Technology II",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4207",
                    name: "Telecommunication Systems",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4208",
                    name: "Fiber Optics Techniques",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4216",
                    name: "Energy and Environment",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 4201",
                    name: "Entrepreneurship",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 4202",
                    name: "Human Resources Management",
                    credits: 2,
                    type: "O",
                },
            ],
            Y4S2: [
                {
                    code: "EET 4818",
                    name: "Undergraduate Project",
                    credits: 4,
                    type: "C",
                },
                {
                    code: "EET 4210",
                    name: "Electronic Product Design",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "EET 4217",
                    name: "Electrical Machines and Drives",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4209",
                    name: "High Voltage Engineering",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4311",
                    name: "Internet Technology and Applications",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "EET 4312",
                    name: "Power System Analysis",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "EET 4213",
                    name: "Antenna and Propagation",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4214",
                    name: "Wireless Communication",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4215",
                    name: "Mechatronics",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4219",
                    name: "Green Energy and Zero Emission Concepts",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "EET 4220",
                    name: "Graphical Programming and Data Acquisition",
                    credits: 2,
                    type: "O",
                },
            ],
        },
    },
    MTT: {
        name: "Materials Technology",
        semesters: {
            Y1S1: [
                {
                    code: "CMT 1301",
                    name: "Fundamentals of Physics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1302",
                    name: "Fundamentals of Chemistry for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1303",
                    name: "Fundamentals of Mathematics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1304",
                    name: "Fundamentals of Computer for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1205",
                    name: "Communication Skills I (English)",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1201",
                    name: "Personality Development (Soft Skills)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1202",
                    name: "Presentation Skills",
                    credits: 2,
                    type: "C",
                },
            ],
            Y1S2: [
                {
                    code: "ENT 1301",
                    name: "Introduction to Basic Electronics",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "ENT 1302",
                    name: "Fundamentals of Electricity and Magnetism",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1307",
                    name: "Mathematics for Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 1208",
                    name: "Computer Programming for Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ENT 1204",
                    name: "Workshop Technology I",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 1209",
                    name: "Communication Skills II",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 1203",
                    name: "Principles of Management",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 1204",
                    name: "Health and Wellbeing",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ENT 1203",
                    name: "Engineering Drawing",
                    credits: 2,
                    type: "C",
                },
            ],
            Y2S1: [
                {
                    code: "MTT 2201",
                    name: "Fundamentals of Solid State Physics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2202",
                    name: "Chemistry for Materials Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2203",
                    name: "Introduction to Ceramic Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2204",
                    name: "Computer Aided Design (CAD)",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CMT 2306",
                    name: "Mathematics for Technology II",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2301",
                    name: "Fundamentals of Statistics for Technology",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "CMT 2202",
                    name: "Communication Skills III",
                    credits: 2,
                    type: "Non GPA",
                },
                {
                    code: "CML 2206",
                    name: "Indigenous Technology",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2202",
                    name: "Engineering Economics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "ICT 2304",
                    name: "Object Oriented Programming",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 2206",
                    name: "Graphical Programming",
                    credits: 2,
                    type: "O",
                },
            ],
            Y2S2: [
                {
                    code: "MTT 2210",
                    name: "Mechanical Behavior of Materials",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2311",
                    name: "Ceramic Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "MTT 2205",
                    name: "Introduction to Metallurgy",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2207",
                    name: "Measurements, Error Analysis and Instrumentation",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2108",
                    name: "Chemical Engineering Sciences",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "MTT 2209",
                    name: "Introduction to Polymer Technology",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 2112",
                    name: "Introduction to Thermodynamics",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "CMT 2203",
                    name: "Computational Mathematics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML 2204",
                    name: "Foreign Language",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2208",
                    name: "Introduction to Marketing",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 2205",
                    name: "Ethics in Science and Technology",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "ICT 2206",
                    name: "Multimedia and Web Technology",
                    credits: 2,
                    type: "O",
                },
            ],
            Y3S1: [
                {
                    code: "MTT 3308",
                    name: "Polymer Technology I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "MTT 3307",
                    name: "Metallurgy I",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "MTT 3306",
                    name: "Ceramic Technology II",
                    credits: 3,
                    type: "C",
                },
                {
                    code: "MTT 3202",
                    name: "Degradation of Materials",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 3103",
                    name: "Ceramic Pilot Plant Practices",
                    credits: 1,
                    type: "O",
                },
                {
                    code: "MTT 3204",
                    name: "Workshop Technology II",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 3212",
                    name: "Non Destructive Testing of Materials",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 3111",
                    name: "Thermodynamics for Materials Technology",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "CML 3101",
                    name: "Legal and Patent aspects",
                    credits: 1,
                    type: "O",
                },
            ],
            Y3S2: [
                {
                    code: "CML 3102",
                    name: "Industrial Safety",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "MTT 3609",
                    name: "Industrial Training",
                    credits: 6,
                    type: "C",
                },
            ],
            Y4S1: [
                {
                    code: "MTT 4201",
                    name: "Fluid Mechanics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 4121",
                    name: "Research Methodology and Scientific Writing",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "MTT 4303",
                    name: "Ceramic Technology III",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 4219",
                    name: "Applied Mechanics",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 4104",
                    name: "Glass Technology",
                    credits: 1,
                    type: "O",
                },
                {
                    code: "MTT 4305",
                    name: "Polymer Technology II",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 4106",
                    name: "Mineral Processing",
                    credits: 1,
                    type: "O",
                },
                {
                    code: "MTT 4307",
                    name: "Metallurgy II",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 4820",
                    name: "Research Project",
                    credits: 0,
                    type: "C",
                },
                {
                    code: "MTT 4108",
                    name: "Directed Reading",
                    credits: 1,
                    type: "O",
                },
                { code: "MTT 4109", name: "Seminar", credits: 1, type: "O" },
                {
                    code: "MTT 4210",
                    name: "Work Shadowing",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "CML 4201",
                    name: "Entrepreneurship",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "CML4202",
                    name: "Human Resource Management",
                    credits: 2,
                    type: "O",
                },
            ],
            Y4S2: [
                {
                    code: "MTT 4820",
                    name: "Research Project",
                    credits: 8,
                    type: "C",
                },
                {
                    code: "MTT 4311",
                    name: "Advanced Materials",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 4312",
                    name: "Advanced Instrumental Techniques and Characterization of Materials",
                    credits: 3,
                    type: "O",
                },
                {
                    code: "MTT 4213",
                    name: "Manufacturing Systems",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "MTT 4114",
                    name: "Quality Management",
                    credits: 1,
                    type: "C",
                },
                {
                    code: "MTT 4215",
                    name: "Cleaner Production",
                    credits: 2,
                    type: "C",
                },
                {
                    code: "MTT 4216",
                    name: "Industrial Metrology",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "MTT 4217",
                    name: "Composite Materials",
                    credits: 2,
                    type: "O",
                },
                {
                    code: "MTT 4218",
                    name: "Paint Technology",
                    credits: 2,
                    type: "O",
                },
            ],
        },
    },
};

export default programs;
